"""Answering-domain entities.

Business nouns of the agent layer:

- `Question` — the user's input, with the `request_id` captured for
  traceability (FR-013).
- `RetrievedChunk` — a `Chunk` plus its similarity score to a
  `Question`.
- `Confidence` — the literal type the agent uses to signal whether
  the answer is grounded in retrieved context.
- `Answer` — the agent's final response: a string plus a
  confidence tag and a trace of node visits.
- `AgentState` — the Pydantic state passed between LangGraph
  nodes. Per plan § Phase 0 / item 1, LangGraph 1.2.x's
  Pydantic-state path is used so we get free validation and
  consistent docstring tooling.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ..shared.retrieval import RetrievedChunk as _SharedRetrievedChunk

# Re-export for the canonical agent-side import path. The
# canonical definition now lives in `domain/shared/retrieval.py`
# because both ingestion's `VectorStore.query` and answering's
# `Retriever` ports return `list[RetrievedChunk]` (post WP01
# review v1 Issue 8 fix).
RetrievedChunk = _SharedRetrievedChunk

Confidence = Literal["high", "low"]
"""Whether the answer is grounded in retrieved context.

- `"high"` — retrieved chunks answered the question.
- `"low"` — retrieval was empty or below threshold; the answer is
  the static refusal string.
"""


class Question(BaseModel):
    """The raw user input, normalised at the API edge.

    Attributes:
        text: The question text (1-2000 characters, per FR-001).
        request_id: A unique id per request, generated by
            `RequestIdMiddleware` (WP02). Echoed in the
            response header `X-Request-Id` and bound to every
            log line (FR-013).
    """

    model_config = ConfigDict(frozen=True)

    text: str = Field(min_length=1, max_length=2000)
    request_id: str = Field(min_length=1)


# `RetrievedChunk` is defined in `domain/shared/retrieval.py`
# (post WP01 review v1 Issue 8) and re-exported at the top of
# this module for the canonical agent-side import path used by
# WP02+.


class Answer(BaseModel):
    """The agent's final response.

    Attributes:
        text: The answer string (or the static refusal string when
            `confidence == "low"`).
        confidence: `"high"` if retrieved chunks answered the
            question, `"low"` otherwise.
        trace: The list of node names the agent visited in order
            (e.g. `["retrieve", "guard", "generate"]`). Surfaced to
            the API caller for observability.
        top_similarity: The top similarity score across the
            retrieved chunks, or `0.0` when retrieval was empty.
            Used as the Prometheus gauge
            `retrieval_similarity_top1` (FR-014).
    """

    model_config = ConfigDict(frozen=True)

    text: str = Field(min_length=1)
    confidence: Confidence
    trace: list[str] = Field(default_factory=list)
    top_similarity: float = Field(ge=0.0, le=1.0, default=0.0)


class AgentState(BaseModel):
    """The Pydantic state passed between LangGraph nodes.

    Used as the schema for `langgraph.graph.StateGraph` (LangGraph
    1.2.x supports Pydantic state natively — verified by T001).
    Each node returns a **partial** state update; LangGraph applies
    the update to the existing state.

    Attributes:
        question: The user's question text.
        retrieved_chunks: Output of the `retrieve` node; empty
            before that node runs.
        answer: Output of the `generate` or `refuse` node; empty
            before one of those runs.
        confidence: `"high"` after a generate, `"low"` after a
            refuse. Defaults to `"low"` because the safer default
            when no work has been done is to refuse.
        trace: Names of nodes visited so far, in order.
    """

    model_config = ConfigDict(frozen=False)  # LangGraph mutates state.

    question: str = ""
    retrieved_chunks: list[RetrievedChunk] = Field(default_factory=list)
    answer: str = ""
    confidence: Confidence = "low"
    trace: list[str] = Field(default_factory=list)
    # Per AGENTS.md 6.3 -- a single request_id propagates through
    # every layer that touches a request. The middleware sets it
    # on the inbound edge; the AnsweringService copies it from
    # its parameter; LangGraph nodes read it from the state.
    request_id: str = ""


__all__ = [
    "Answer",
    "AgentState",
    "Confidence",
    "Question",
    "RetrievedChunk",
]